# values.yaml
replicaCount: 1

image:
  repository: quay.io/pkjoon/ui
  tag: 1.0
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080

route:
  host: vote-ui-microservices.apps-crc.testing
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge