apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-api
  namespace: openshift-gitops
spec:
  destination:
    namespace: microservices
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: charts
    repoURL: https://github.com/poonamkadian/gitops
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    - Validate=true
    - SkipHooks=false
  #helm:
  #  valueFiles:
  #  - helm-chart/values.yaml
